#!/usr/bin/env python3
"""Regression check for deterministic FPF graph generation."""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

from scripts.filesystem_policy import temporary_workspace

ROOT = Path(__file__).resolve().parents[3]
GENERATOR_MODULE = "scripts.build_fpf_obsidian_graph"
SOURCE = "# Part A - Example\n\n## A.1 - First page\n\nA.2 links here.\n\n## A.2 - Second page\n"
RISK_SOURCE = '''# Part A - Example

## A.1 - Rendering risks

[A.2: adjacent bracket reference].

| Target | Empty |
| --- | --- |
| A.2 | |

```markdown
## A.99 - Fenced false heading
```

# | table-shaped false heading

## A.2 - Real second page
'''
REVISION = "test-revision-0001"
GENERATED_ON = "2026-08-02"


def tree_bytes(path: Path) -> dict[str, bytes]:
    return {item.relative_to(path).as_posix(): item.read_bytes() for item in sorted(path.rglob("*")) if item.is_file()}


def build(source: Path, output: Path) -> None:
    result = subprocess.run([sys.executable, "-m", GENERATOR_MODULE, "--source", str(source), "--source-revision", REVISION, "--generated-on", GENERATED_ON, "--out", str(output), "--clean"], cwd=ROOT, capture_output=True, text=True)
    if result.returncode:
        raise SystemExit(result.stderr or result.stdout)


def verify_replayability(root: Path, source: Path) -> dict[str, bytes]:
    first = root / "first" / "FPF-Knowledge-Graph"
    second = root / "second" / "FPF-Knowledge-Graph"
    build(source, first)
    build(source, second)
    first_tree = tree_bytes(first)
    if first_tree != tree_bytes(second):
        raise SystemExit("checkout location changed generated bytes")
    return first_tree


def verify_clean_removes_stale(root: Path, source: Path) -> None:
    output = root / "clean" / "FPF-Knowledge-Graph"
    build(source, output)
    source.write_text("# Part A - Example\n\n## A.1 - First page\n", encoding="utf-8")
    build(source, output)
    if any('fpf_id: "A.2"' in path.read_text() for path in output.rglob("*.md")):
        raise SystemExit("clean rebuild retained a deleted source carrier")


def verify_rendering_regressions(root: Path, source: Path) -> None:
    output = root / "risks" / "FPF-Knowledge-Graph"
    source.write_text(RISK_SOURCE, encoding="utf-8")
    build(source, output)
    text = "\n".join(path.read_text() for path in output.rglob("*.md"))
    if "[[[" in text or "]]]" in text:
        raise SystemExit("bracket reference produced malformed nested wiki-link syntax")
    if 'fpf_id: "A.99"' in text or text.count('fpf_id: "A.2"') != 1:
        raise SystemExit("fenced or table-shaped text was parsed as a heading")
    table_lines = [line for line in text.splitlines() if line.startswith("|")]
    aliased = any(re.search(r"\[\[[^\]]+\|[^\]]+\]\]", line) for line in table_lines)
    if "| Empty |" in text or aliased:
        raise SystemExit("table cleanup or wiki-link alias escaping regressed")


def main() -> int:
    with temporary_workspace() as temp:
        root = Path(temp)
        source = root / "FPF-Spec.md"
        source.write_text(SOURCE, encoding="utf-8")
        output = root / "first" / "FPF-Knowledge-Graph"
        first_tree = verify_replayability(root, source)
        report = json.loads((output / "00_Index" / "FPF - Validation Report.json").read_text(encoding="utf-8"))
        if report["source_sha256"] != hashlib.sha256(source.read_bytes()).hexdigest():
            raise SystemExit("report SHA-256 does not match exact source bytes")
        if report["source"] != source.name or report["out_dir"] != output.name:
            raise SystemExit("report contains location-sensitive source or output identity")
        for page in output.rglob("*.md"):
            text = page.read_text(encoding="utf-8")
            for key in ("source_revision", "source_sha256", "generated_on"):
                if f'{key}: "{report[key]}"' not in text:
                    raise SystemExit(f"provenance mismatch in {page}")
        verify_clean_removes_stale(root, source)
        source.write_text(SOURCE, encoding="utf-8")
        verify_rendering_regressions(root, source)
    print("reproducible generation: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
